name: Bar
on:
  workflow_run:
    workflows: [ "Foo" ]
    types: [ completed ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bar:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo bar ${{ github.event.action }}
