name: Bar
on:
  workflow_run:
    workflows: [ "Foo" ]
    types: [ completed ]
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]
    types: [ "opened", "synchronize" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bar:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo bar ${{ github.event_name }}
