name: Bar
on:
  workflow_run:
    workflows: [ "Foo" ]
    types: [ completed ]
    paths:
      - "tmp.txt"
  push:
    branches: ["main"]
    paths:
      - "**"
      - "!tmp.txt"
  pull_request:
    branches: ["main"]
    types: [ "opened", "synchronize" ]
    paths:
      - "**"
      - "!tmp.txt"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bar:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo bar ${{ github.event.action }}
