name: Foo Test
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [ "opened", "synchronize" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo foo
